### ISSUE TITLE
Rest API data issues?

### ISSUE THREAD

**Issue by fitzoh** [HHS/uts-rest-api#2]
`/content/current/CUI/C3540695` is the cui for [https://en.wikipedia.org/wiki/Anatomical_Therapeutic_Chemical_Classification_System](ATC).

If I look it up in the online browser, I get 19 relationships, yet the json payload shows zero relationships.
This seems to be a common issue amongst ATC CUI's.

```
{  
   "pageSize":25,
   "pageNumber":1,
   "pageCount":1,
   "result":{  
      "classType":"Concept",
      "ui":"C3540695",
      "suppressible":false,
      "dateAdded":"11-18-2013",
      "majorRevisionDate":"08-10-2015",
      "status":"R",
      "semanticTypes":[  
         "T170: Intellectual Product"
      ],
      "atomCount":5,
      "attributeCount":0,
      "cvMemberCount":0,
      "atoms":"https://uts-ws.nlm.nih.gov/rest/content/2015AB/CUI/C3540695/atoms",
      "definitions":"NONE",
      "relations":"NONE",
      "defaultPreferredAtom":"https://uts-ws.nlm.nih.gov/rest/content/2015AB/CUI/C3540695/atoms/preferred",
      "relationCount":0,
      "name":"Anatomical Therapeutic Chemical (ATC)-classification system"
   }
}
```

```
Concept: [C3540695]  Anatomical Therapeutic Chemical (ATC)-classification system

Semantic Type
    Synonyms (2)
    Relations (19)    REL | RELA | RSAB| String | CUI
```

**Comment by stevenemrick** [comment]
Andrew - if you're trying to navigate from the ATC tree-top, this is the URL you want:
https://uts-ws.nlm.nih.gov/rest/content/current/source/SRC/V-ATC/relations?ticket=ST...

Sometimes NLM must create 'SRC' atoms at the root of a vocabulary if the vocabulary itself does not provide them.  The relations you see in the browser are actually from the SRC atom and not attached to the CUI itself. 

Also - what is your use case with ATC in the Metathesaurus?  Most of the time if you're navigating from a source-asserted identifier (in your case the ATC code), you want to use that as the focal point to retrieve relations rather than a CUI.

**Comment by fitzoh** [comment]
I was looking at the hierarchical nature of ATC and being able to drill down the and traverse the parent/child graph. I mentioned ATC in the issue because I was expecting it to be the root node of the tree.

For instance, `content/2015AB/source/ATC/A` has no relationships, `content/2015AB/source/ATC/A01` has no relationships, and `content/2015AB/source/ATC/A01A` has no relationships, when I would expect them to have parent/child relationships between `A <-> A01 <-> A01A` as seen [here](http://www.whocc.no/atc_ddd_index/?code=A01AA&showdescription=yes).

**Comment by stevenemrick** [comment]
Yes - so there are a few things here.  When you want to traverse parent/child relationships, use the [parents and children endpoint](https://documentation.uts.nlm.nih.gov/rest/parents-and-children/index.html) or the [descendants endpoint](https://documentation.uts.nlm.nih.gov/rest/ancestors-and-descendants/index.html).
So normally, you would want to use /source/ATC/A/children or source/ATC/A/descendants to compute children or transitive closure.  Some of the nodes work and some don't due to a bug we found with the way contextual relationships are computed in ATC that has to do with some unique data conditions in ATC related to term type ranking.  Our developers are already looking into this and should have a fix soon.   I've created an issue for this - #3. Thanks for reporting!
