### ISSUE TITLE
UMLS Atoms API causing ECONNRESET error

### ISSUE THREAD

**Issue by sakethk** [HHS/uts-rest-api#31]
I am trying to make multiple requests using a nodejs app. However, it works fine for a few simultaneous requests but when requests increases it throws ECONNRESET error and doesn't return a response of single request. what might be causing an issue?

**Comment by danizen** [comment]
Two possibilities:

* Due to our licensing agreements, a new service ticket (ST) must be obtained and used for each API call.  It may be due to a callback ordering issue/race condition, this is not happening.

* We have an [acceptable use policy](https://documentation.uts.nlm.nih.gov/terms-of-service.html) allowing 20 requests per second per IP Address.  It is up to you to implement a token buffer algorithm to comply with the acceptable use policy.
