### ISSUE TITLE
Can a Service Ticket be used to download UMLS?

### ISSUE THREAD

**Issue by tholu** [HHS/uts-rest-api#32]
Unfortunately the [Terminology Download Script](https://download.nlm.nih.gov/rxnorm/terminology_download_script.zip) no longer works. Looking for an alternative, I saw that the current download process involves a Service Ticket as well. 

However, https://download.nlm.nih.gov/umls/kss/2020AA/umls-2020AA-full.zip?ticket=ST-... does not work with `curl`. Any pointers how to download this file via curl/wget/a script?

**Comment by danizen** [comment]
@tholu, I forwarded your request internally, but I think you'd be better served by opening an issue at https://support.nlm.nih.gov/.   RxNorm and UMLS are both products of OCCS/MLB, but this repository was a product of another dept., and I am just a caretaker here.

In terms of authentication and authorization, a single line of curl won't work since you need to get a new ticket from the authentication service and then make the call.

**Comment by wkhat-engineer** [comment]
@tholu If you make sure that when you generate your ST you use the service parameter with one of the URLs from the terminology download script, you can get a ticket that will allow you to then download it (using a GET request). Not documented though, so not sure how long that behavior will continue for, especially if the response is right, that they are managed by other teams.

**Comment by danizen** [comment]
@tholu, what programming language are you using?  If you are using Python, I wrote some code outside work at https://github.com/danizen/nlm-demo-notebook that automatically gets a new ST for each request.  If you are not using Python, it may give you some idea.

Disclaimer - this post is done as a developer and not in my role at NLM.
